/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MySummary } from '../../models/my-summary';

export interface GetMySummary$Params {
}

export function getMySummary(http: HttpClient, rootUrl: string, params?: GetMySummary$Params, context?: HttpContext): Observable<StrictHttpResponse<MySummary>> {
  const rb = new RequestBuilder(rootUrl, getMySummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MySummary>;
    })
  );
}

getMySummary.PATH = '/me/summary';
