/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaderboardEntry } from '../../models/leaderboard-entry';

export interface GetLeaderboard$Params {
}

export function getLeaderboard(http: HttpClient, rootUrl: string, params?: GetLeaderboard$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaderboardEntry>>> {
  const rb = new RequestBuilder(rootUrl, getLeaderboard.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeaderboardEntry>>;
    })
  );
}

getLeaderboard.PATH = '/leaderboard';
