/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface AuthResponse {
  accessToken: string;

  /**
   * Segundos de vida del access token
   */
  expiresIn: number;
  user: User;
}
