/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LeaderboardEntry {
  displayName: string;
  exactHits: number;
  outcomeHits: number;
  points: number;
  position: number;
  scoredPredictions: number;
  userId: number;
}
