/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MySummary {
  exactHits: number;
  outcomeHits: number;

  /**
   * Partidos abiertos sin predicción del usuario.
   */
  pendingPredictions: number;
  points: number;
  position: number;
  totalParticipants: number;
}
