/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * RFC 9457
 */
export interface ProblemDetail {
  detail?: string;

  /**
   * Errores de validación por campo (solo en 400).
   */
  errors?: Array<{
'field'?: string;
'message'?: string;
}>;
  instance?: string;
  status?: number;
  title?: string;
  type?: string;
}
