/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  displayName: string;
  email: string;

  /**
   * Al menos una letra y un número.
   */
  password: string;
}
