/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Team {
  code: string;

  /**
   * ISO 3166-1 alpha-2 en minúsculas
   */
  flagCode: string;
  name: string;
}
