/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface User {
  displayName: string;
  email: string;
  id: number;
  role: Role;
}
