/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminMatch } from './models/admin-match';
export type { AuthResponse } from './models/auth-response';
export type { DeleteAccountRequest } from './models/delete-account-request';
export type { LeaderboardEntry } from './models/leaderboard-entry';
export type { LoginRequest } from './models/login-request';
export type { Match } from './models/match';
export type { MatchStatus } from './models/match-status';
export type { MySummary } from './models/my-summary';
export type { Prediction } from './models/prediction';
export type { PredictionHistory } from './models/prediction-history';
export type { PredictionHistoryItem } from './models/prediction-history-item';
export type { ProblemDetail } from './models/problem-detail';
export type { RegisterRequest } from './models/register-request';
export type { RegisterResultRequest } from './models/register-result-request';
export type { Role } from './models/role';
export type { Score } from './models/score';
export type { Team } from './models/team';
export type { User } from './models/user';
