-- Esquema inicial. Diseño documentado en specs/database.md

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(254) not null,
    display_name  varchar(40)  not null,
    password_hash varchar(100) not null,
    role          varchar(10)  not null default 'USER',
    created_at    timestamptz  not null default now(),
    constraint uk_users_email unique (email),
    constraint ck_users_email_lowercase check (email = lower(email)),
    constraint ck_users_role check (role in ('USER', 'ADMIN'))
);

create table refresh_tokens (
    id          bigint generated by default as identity primary key,
    user_id     bigint      not null references users (id) on delete cascade,
    token_hash  varchar(64)    not null,
    expires_at  timestamptz not null,
    revoked_at  timestamptz,
    created_at  timestamptz not null default now(),
    constraint uk_refresh_tokens_hash unique (token_hash)
);
create index ix_refresh_tokens_user on refresh_tokens (user_id);

create table teams (
    id         bigint generated by default as identity primary key,
    code       varchar(3)  not null,
    name       varchar(60) not null,
    flag_code  varchar(2)  not null,
    group_code varchar(1)     not null,
    constraint uk_teams_code unique (code)
);

create table matches (
    id                   bigint generated by default as identity primary key,
    group_code           varchar(1)     not null,
    matchday             integer     not null,
    home_team_id         bigint      not null references teams (id),
    away_team_id         bigint      not null references teams (id),
    kickoff_at           timestamptz not null,
    venue                varchar(80),
    status               varchar(10) not null default 'SCHEDULED',
    home_goals           integer,
    away_goals           integer,
    result_registered_at timestamptz,
    version              bigint      not null default 0,
    constraint ck_matches_distinct_teams check (home_team_id <> away_team_id),
    constraint ck_matches_status check (status in ('SCHEDULED', 'FINISHED')),
    constraint ck_matches_matchday check (matchday between 1 and 3),
    constraint ck_matches_goals_range check (
        (home_goals is null or home_goals between 0 and 20) and
        (away_goals is null or away_goals between 0 and 20)),
    constraint ck_matches_result_consistency check (
        (status = 'SCHEDULED' and home_goals is null and away_goals is null) or
        (status = 'FINISHED' and home_goals is not null and away_goals is not null))
);
create index ix_matches_kickoff on matches (kickoff_at);

create table predictions (
    id          bigint generated by default as identity primary key,
    user_id     bigint      not null references users (id) on delete cascade,
    match_id    bigint      not null references matches (id) on delete cascade,
    home_goals  integer     not null,
    away_goals  integer     not null,
    points      integer,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    constraint uk_predictions_user_match unique (user_id, match_id),
    constraint ck_predictions_goals_range check (home_goals between 0 and 20 and away_goals between 0 and 20),
    constraint ck_predictions_points check (points is null or points >= 0)
);
create index ix_predictions_match on predictions (match_id);
