/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminMatch } from '../../models/admin-match';

export interface ListMatchesForAdmin$Params {
}

export function listMatchesForAdmin(http: HttpClient, rootUrl: string, params?: ListMatchesForAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AdminMatch>>> {
  const rb = new RequestBuilder(rootUrl, listMatchesForAdmin.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AdminMatch>>;
    })
  );
}

listMatchesForAdmin.PATH = '/admin/matches';
